- name: gather facts
  hosts: local
  connection: local
  # ansible gather all info about target server , before executing any other facts
  tasks:
    - name: facts
      ansible.builtin.debug:
        msg: "{{ ansible_facts }}"