- name: file level varaiable 
  hosts: local
  connection: local
  vars_files:
    - course.yaml
  tasks:
    - name: file level variables
      ansible.builtin.debug:
        msg: " course name is: {{ course }}, duration is: {{ duration }} and trainer is: {{ trainer }}"