- name: functions
  hosts: local
  connection: local
  vars:
    technologies: devops,python,java,shell,linux
  
  tags:
    Application: python
    environment: dev 
  list_tags:
    - key: Application
      value: payment
    - key: environment
      value: dev
  tasks:
    - name: default variables
      ansible.builtin.debug:
        msg: "Hello, {{ name | default('Ramesh') }}" # default value function 
    - name: convert string to list 
      ansible.builtin.debug:
        msg: "technologies are: {{ technologies| split(',') }}"
    - name: convert map to list 
      ansible.builtin.debug:
        msg: "tags: {{ tags | dict2items }}"
    - name: convert list to map
      ansible.builtin.debug:
        msg: "list_tags are: {{ tags | items2dict }}"
    - name: read the yaml file and store as variables
      ansible.builtin.set_fact:
        installation.yaml: "{{ lookup('file','installation.yaml')|from_yaml }}"
    - name: convert to json from yaml file
      ansible.builtin.debug:
        msg: "{{ installation.yaml | to_json }}"
    - name: convert to json file from yaml and save into a file
      ansible.builtin.copy:
        dest: ./installation.json
        content: "{{ installation.yaml | to_nice_json }}"
    
