- name: functions
  hosts: local
  connection: local
  vars:
    technologies: devops,python,java,shell,linux
    tags:
      Application: python
      environment: dev 
    list_tags:
      - key: Application
        value: payment
      - key: environment
        value: dev
    name: chanDana
    gmail: REBBAchandana@gmail.com
    ip_address: 123.456.789
  tasks:
    - name: default variables
      ansible.builtin.debug:
        msg: "Hello, {{ user | default('Ramesh') }}" # default value function 
    - name: convert string to list 
      ansible.builtin.debug:
        msg: "technologies are: {{ technologies| split(',') }}"
    - name: convert map to list 
      ansible.builtin.debug:
        msg: "tags: {{ tags | dict2items }}"
    - name: convert list to map
      ansible.builtin.debug:
        msg: "list_tags are: {{ list_tags | items2dict }}"
    - name: read the yaml file and store as variables
      ansible.builtin.set_fact:
        installation_yaml: "{{ lookup('file','installation.yaml')|from_yaml }}"
    - name: convert to json from yaml file
      ansible.builtin.debug:
        msg: "{{ installation_yaml | to_json }}"
    - name: convert to json file from yaml and save into a file
      ansible.builtin.copy:
        dest: ./installation.json
        content: "{{ installation_yaml | to_nice_json }}"
    - name: convert to upper case 
      ansible.builtin.debug:
        msg: "{{ name | upper }}"
    - name: convert to lowercase 
      ansible.builtin.debug:
        msg: "{{ gmail | lower }}"
    - name: check ipaddress is valid or not
      ansible.builtin.debug:
        msg: "{{ ip_address | ansible.utils.ipv4 }}" 
    - name: grep for root using command 
      ansible.builtin.command: cat /etc/passwd | grep root
      register: command_output
      ignore_errors: true
    - name: print command command_output
      ansible.builtin.debug:
        msg: "{{ command_output }}"
    - name: grep for root using shell 
      ansible.builtin.shell: cat /etc/passwd | grep root
      register: shell_output
    - name: print shell output
      ansible.builtin.debug:
        msg: "{{ shell_output }}" 
    - name: redirect output using command
      ansible.builtin.command: ls -ltr > /tmp/output.txt
      register: redirect_command_output
      ignore_errors: true
    - name: print command redirect_output
      ansible.builtin.debug:
        msg: "{{ redirect_command_output }}"  
    - name: redirect output using shell
      ansible.builtin.shell: ls -ltr > /tmp/output.txt
      register: redirect_shell_output

    - name: print shell redirect_output
      ansible.builtin.debug:
        msg: "{{ redirect_shell_output }}" 
    
