- name: installing package and starting services
  hosts: frontend
  become: true
  tasks:
    - name: installing package
      ansible.builtin.package:
        name: mysql
        state: present
    - name: starting and enabling services
      ansible.builtin.service:
        name: mysqld
        enabled: yes
        state: started