- name: play level varaiable 
  hosts: local
  connection: local
  vars:
    course: ansible
    duration: 9 hrs
    trainer: shiva kumar
  tasks:
    - name: play level variables
      ansible.builtin.debug:
        msg: " course name is: {{ course }}, duration is: {{ duration }} and trainer is: {{ trainer }}"
