- name: play level varaiable 
  hosts: local
  connection: local 
  vars_prompt:
    - name: username
      prompt: what is your name
      private: false
    - name: password
      prompt: what is your password
      private: false
  tasks:
    - name: prompt level variables
      ansible.builtin.debug:
        msg: "usename is : {{ username }}, password is: {{ password }}"
        
